export enum IPCMainEvents {
    INIT_CREATE_NEW_PROJECT = "INIT_CREATE_NEW_PROJECT",
    INIT_OPEN_PROJECT = "INIT_OPEN_PROJECT",
    INIT_SAVE_PROJECT = "INIT_SAVE_PROJECT"
}

export enum IPCRendererEvents {
    INIT_SET_CAN_SAVE = "INIT_SET_CAN_SAVE",
    INIT_SET_PROJECT_INFO = "INIT_SET_PROJECT_NAME"
}
